"""The global exercise library (Phase 7), vendored from the public-domain
`yuhonas/free-exercise-db` (~870 exercises with Everkinetic illustrations).

The data lives in ``data/exercises.json`` and is (re)generated by
``backend.workouts.import_library``. Each entry: ``name`` (English, canonical),
``name_de`` (best-effort German display name), ``category``, ``equipment``,
``primary_muscles``, ``secondary_muscles``, ``instructions``, ``image_url``
(relative free-exercise-db path; the frontend prefixes the CDN base).
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_DATA_FILE = Path(__file__).parent / "data" / "exercises.json"


@lru_cache(maxsize=1)
def _load() -> list[dict]:
    return json.loads(_DATA_FILE.read_text())


# Loaded lazily and cached; access as a list of dicts.
LIBRARY_EXERCISES: list[dict] = _load()
